# NEW_CHAT_ELEMENT = '//*[@id="app"]/div/div[3]/div/div[3]/header/header/div/span/div/div[1]/button'
NEW_CHAT_ELEMENT = '//*[@data-icon="new-chat-outline"]'
NUMBER_BOX = '/html/body/div[1]/div/div/div/div/div[3]/div/div[3]/div[1]/div/span/div/span/div/div[1]/div[2]/div'
MESSAGE_BOX = '/html/body/div[1]/div/div/div/div/div[3]/div/div[5]/div/footer/div[1]/div/span/div/div/div/div[3]/div[1]/p'
CAPTION_BOX = '//*[@id="app"]/div/div[3]/div/div[2]/div[2]/span/div/div/div/div[2]/div/div[1]/div[3]/div/div/div[1]/div[@contenteditable="true" and @role="textbox"]'
NO_CHAT_FOUND = '//span[contains(text(),"No results found for ") and @dir="auto"]'
HEADER_BACK = '//header/div[1]/div[1]/div[1]/span[@data-icon="back"]'
# HEADER_BACK = '//*[@id="app"]/div/div[3]/div/div[2]/div[1]/span/div/span/div/header/div/div[1]/div/span[@data-icon="back"]'
NEW_CHAT = '/html/body/div[1]/div/div/div/div/div[3]/div/div[3]/div[1]/div/span/div/span/div/div[2]/div[2]/div/div/div[2]/div/div/div[2]'
CONTACT_BOX = '//*[@id="side"]/div[1]/div/div[2]/div[2]/div/div'
ATTACH_BNT = '/html/body/div[1]/div/div/div/div/div[3]/div/div[5]/div/footer/div[1]/div/span/div/div/div/div[1]/div/span/button/div/div/div[1]/span'
ADD_FILE = '//*Button[@title="Add file"]'
IMG_BNT = '/html/body/div[1]/div/div/div/div/span[6]/div/ul/div/div/div[2]/li/div/span'
IMG_INPUT = '/html/body/div[1]/div/div/div/div/span[6]/div/ul/div/div/div[2]/li'
SEND_BNT = '/html/body/div[1]/div/div/div/div/div[3]/div/div[3]/div[2]/div/span/div/div/div/div[2]/div/div[2]/div[2]/span/div/div[1]/span'
ATTACH_MULTI_BNT = '/html/body/div[1]/div/div/div/div/div[3]/div/div[3]/div[2]/div/span/div/div/div/div[2]/div/div[2]/div[1]/button'